#!/bin/bash
# wallpaper
# Created Fri Jan 18 10:25:13 AKST 2019
# by Raymond E. Marcil <marcilr@gmaik.com>
#
# Script to set backfground wallpaper under Xfce v4.12
#
# $ xfce4-panel --version
# xfce4-panel 4.12.1 (Xfce 4.12)
# ...
# $
#
# Links
# =====
# set the desktop wallpaper under Xfce4
# https://ubuntuincident.wordpress.com/2015/03/08/set-the-desktop-wallpaper-under-xfce4/
#

# =============
# Configuration
# =============

#
# Enable debugging by assigning DEBUG to any value
# i.e. To display just comment out DEBUG.
#
DEBUG=true

# Directory with wallpaper to randomly select and set
WALLPAPERDIR=~/.wallpaper


# ========
# Binaries
# ========
GREP=/bin/grep
XFCONFQUERY=/usr/bin/xfconf-query


#
# debug()
#
debug() {
  [[ ! -z "${DEBUG}" ]] && echo "debug() ${1}"
}

#
# random()
# Get a random image for the WALLPAPERDIR directory
#
random() {

  debug "random() start"

  debug "random() end"

}


# ===============================
# MAIN
# ==============================

debug "MAIN *** start ***"

#ls ${WALLPAPER}



#
# Loop over list of properties to set to
# absoluted path of wallpaper image.
#
${XFCONFQUERY} -c xfce4-desktop -l | ${GREP} "last-image$" | while read LASTIMAGE; do
  debug "MAIN LASTIMAGE: ${LASTIMAGE}"
done

debug "MAIN *** end ***"

